# Default values for go-links.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  ssoEntityId: go-links
  ssoCallbackUrl: https://go.collins.home
  ssoMetadataFileContents: >
    <?xml version="1.0" encoding="UTF-8"?><md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" entityID="https://accounts.google.com/o/saml2?idpid=C01kjpo6x" validUntil="2026-09-15T16:43:33.000Z">
        <md:IDPSSODescriptor WantAuthnRequestsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
          <md:KeyDescriptor use="signing">
            <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
              <ds:X509Data>
                <ds:X509Certificate>MIIDdDCCAlygAwIBAgIGAXvvffRSMA0GCSqGSIb3DQEBCwUAMHsxFDASBgNVBAoTC0dvb2dsZSBJ
                  bmMuMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MQ8wDQYDVQQDEwZHb29nbGUxGDAWBgNVBAsTD0dv
                  b2dsZSBGb3IgV29yazELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWEwHhcNMjEwOTE2
                  MTY0MzMzWhcNMjYwOTE1MTY0MzMzWjB7MRQwEgYDVQQKEwtHb29nbGUgSW5jLjEWMBQGA1UEBxMN
                  TW91bnRhaW4gVmlldzEPMA0GA1UEAxMGR29vZ2xlMRgwFgYDVQQLEw9Hb29nbGUgRm9yIFdvcmsx
                  CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
                  MIIBCgKCAQEAt7Q9dxYvEroHKzbuSiVEAN+bH2n6PufMGYpKB7c52dgnykOo62ifzQFZrOk2ALMA
                  gqlxTgGIEwuFixeqAOCw3N2CoA+EKSPUXyEW+z/oXxqX8phCfFbi80Jha5ZGq+m7QTw0X274tUf2
                  zCX/xeKkjCH9hCPdhfGanYFHE07+nTiNPtw3Q1uoLrbF567xH1yoj5cYmWTszL78o+JKB2v5EDg0
                  fBf13+fYeQ1Ie5PZMvU1U4YTvwKiI3ZnMLloRK0NDPOB/bz0q52miBF9WH052H5QlTAyNlosoxKB
                  H3M4hjzx3BlHaWRKUlq0TovaSInF63oP6jQfc7WDNVvXLLf1dQIDAQABMA0GCSqGSIb3DQEBCwUA
                  A4IBAQCoaEXszPrClc60rwFzUaJkIDx2/yBWmgaavNzmM/JiOwYxfmxqZ/UNGqYEYQtsKYRanr9B
                  Bz/Jl5SltKpvZlePiUdVxvigQLgrLZUQn6CXGjlT5kZvdV4Z5JCts9+cubHMp7YiV9DxRsI6uqSa
                  vJ6HRTtZ/lsx4h0raajtze0LliCIcPyQtAErS0fI2xazLdm/53uvIWBHJdJ4Xj4QsUftZDie3p5L
                  W1U+v3kFpwzYT1ncX+COMnLRT0p+32wBPEu9zc1tdrsG+lKt34zpqKv8duY0ond8vK9uYENkKTjX
                  /HNOKHbR23ARFnrczPaOePv1UL7vn6oAjxFzv9H+9P/k</ds:X509Certificate>
                </ds:X509Data>
              </ds:KeyInfo>
            </md:KeyDescriptor>
            <md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</md:NameIDFormat>
            <md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://accounts.google.com/o/saml2/idp?idpid=C01kjpo6x"/>
            <md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://accounts.google.com/o/saml2/idp?idpid=C01kjpo6x"/>
          </md:IDPSSODescriptor>
        </md:EntityDescriptor>

replicaCount: 1

image:
  repository: ghcr.io/imdevinc/go-links
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: go.collins.home
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
