version: '3'

services:
  web:
    depends_on:
      - jaeger
    build:
      context: .
      dockerfile: ./Dockerfile
    pid: "host"
    ports:
      - "8080:8080"
    volumes:
      - /proc:/host/proc
  go-auto:
    depends_on:
      - web
    image: otel/autoinstrumentation-go
    privileged: true
    pid: "host"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - OTEL_RESOURCE_ATTRIBUTES=service.name=web
      - OTEL_GO_AUTO_TARGET_EXE=/main
      - OTEL_PROPAGATORS=tracecontext,baggage
    volumes:
      - /proc:/host/proc
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
