apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-links.fullname" . }}
  labels:
    {{- include "go-links.labels" . | nindent 4}}
data:
  {{- if .Values.config.ssoEntityId }}
  SSO_ENTITY_ID: {{ .Values.config.ssoEntityId }}
  {{- end }}
  {{- if .Values.config.ssoCallbackUrl }}
  SSO_CALLBACK_URL: {{ .Values.config.ssoCallbackUrl }}
  {{- end }}
  {{- if .Values.config.ssoMetadataFileContents }}
  ssoidpmetadata.xml: |
    {{ .Values.config.ssoMetadataFileContents }}
  {{- end }}